export const BOOK1_VISUAL_ROOT = "public/visuals/book1";

export const BOOK1_CHAPTER_IDS = [
  "ch1",
  "ch2",
  "ch3",
  "ch4",
  "ch5",
  "ch6",
  "ch7",
  "ch8",
  "ch9",
  "ch10",
  "ch11a",
  "ch11b",
];

export const BOOK1_CHARACTERS = [
  {
    id: "barry",
    name: "Barry",
    role: "Narrator and tournament participant",
    kind: "28-year-old ordinary human man from the Western Continent",
    anchors: [
      "ordinary guy",
      "my stat device",
      "stat booster",
      "strapped my crossbow to the back of my backpack",
      "my dagger",
      "my stat booster's screen",
    ],
    facts: [
      "Canon: twenty-eight-year-old ordinary human man from the Western Continent, not visually heroic by default.",
      "Canon: practical traveler with a stat booster/stat device kept in his pocket; it has a small screen that can show stats, time, beeps and emergency prompts.",
      "Canon: carries a practical backpack that starts as ordinary, then becomes enchanted; it can hide contents and later display a magical inventory screen.",
      "Canon: straps a crossbow to the back of his backpack and carries a dagger for emergencies.",
      "Canon attitude: cautious, observant, self-deprecating and fallible, but determined enough to keep moving among much stronger mages.",
      "Design choice: average height and build, plain approachable face, short slightly messy dark brown hair, light stubble, tired but alert eyes.",
      "Design choice: practical worn travel clothing: simple off-white linen shirt, dark brown sleeveless leather vest or jerkin, sturdy dark trousers, leather belt and weathered travel boots.",
      "Design choice: show the stat booster as a palm-sized magical handheld device, similar in silhouette to a small virtual-pet toy or compact old digital organizer, with a small glowing screen showing abstract numeric rows and icons, no readable text.",
      "Design choice: show the backpack as weathered and outwardly ordinary, but subtly enchanted with faint magical seams or a small soft glow.",
      "Avoid: heroic armor, mage robes, noble clothing, sinister sorcerer styling, modern phone design or superhero confidence.",
    ],
  },
  {
    id: "daren",
    name: "Daren",
    role: "Healer in armor",
    kind: "middle-aged human white mage in heavy armor",
    anchors: [
      "healer in armor",
      "heavy armor",
      "head is bald",
      "skin is dark",
      "mid forties",
      "scar on his forehead",
      "use a sword and a shield",
      "white light appear all around him",
      "legendary hero Daren",
    ],
    facts: [
      "Canon: famous white mage and healer known as the healer in armor and legendary savior of the Eastern Continent.",
      "Canon: dark-skinned human man, likely in his mid forties, bald, with an X-shaped scar on his forehead.",
      "Canon: wears heavy armor in combat; his shield and sword are central to his fighting style because he cannot rely on a normal shield spell against weapons.",
      "Canon: uses an enchanted sword and shield, white healing magic and protective barriers; his healing magic appears as bright white light.",
      "Canon attitude: confident, protective, brave and battle-ready, but still human enough to joke, get embarrassed and make mistakes.",
      "Design choice: full heavy adventurer armor with visible joints, dents and travel wear, practical rather than ceremonial.",
      "Design choice: broad, solid stance with sword and shield visible; white magical light should feel like healing/protection, not necromancy or dark sorcery.",
      "Avoid: young knight, hair, noble court armor, priest robes, grimdark villain styling, oversized fantasy spikes or angelic paladin excess.",
    ],
  },
  {
    id: "kate",
    name: "Kate",
    role: "Mage introduced before her name is known",
    kind: "early-twenties human ice mage",
    anchors: [
      "slim, tall figure",
      "long black hair",
      "long sleeved white blouse",
      "green, hooded cloak",
      "strong magical aura",
      "floating ice swords",
    ],
    facts: [
      "Canon: tall, slim human woman in her early twenties, with fair skin and long black hair.",
      "Canon: wears leather pants, a long-sleeved white blouse and a green hooded cloak.",
      "Canon: has a very serious look and a strong magical aura that makes others suspect she is far more dangerous than a normal mage.",
      "Canon: uses precise ice magic, including floating ice swords and ice barriers.",
      "Canon attitude: controlled, guarded, sharp and pragmatic; she should feel dangerous without looking theatrical.",
      "Design choice: fitted travel-worn clothing under the cloak, practical boots and a clean silhouette for fast movement.",
      "Avoid: soft court-dress styling, witch hat, bulky armor, seductive framing, fire magic or friendly tavern energy.",
    ],
  },
  {
    id: "rose",
    name: "Rose",
    role: "Varathian herbalist",
    kind: "mid-twenties human herbalist",
    anchors: ["long auburn hair", "light-brown eyes radiate kindness", "auburn dress", "herbalist", "bowing elegantly"],
    facts: [
      "Canon: beautiful Varathian herbalist in her mid twenties.",
      "Canon: long auburn hair, thin waist, soft feminine features, warm smile and light-brown eyes that radiate kindness.",
      "Canon: wears an auburn dress that matches her hair and bows elegantly when introduced.",
      "Canon: gathers rare herbs, treats sickness and belongs to civilian Thilias life rather than the tournament's warrior culture.",
      "Canon attitude: kind, polite, gentle and brave in a non-combatant way.",
      "Design choice: simple travel-ready herbalist details such as a small herb pouch, clean apron-like sash or modest satchel.",
      "Avoid: battle armor, mage robes, weapon-focused posing, royal gown, seductive framing or grim healer aesthetic.",
    ],
  },
  {
    id: "hadrik",
    name: "Hadrik",
    role: "Giant shapeshifted as a dwarf",
    kind: "giant man shapeshifted into a dwarf",
    anchors: [
      "dressed in leather armor",
      "black beard that reaches down to his chest",
      "big grin",
      "shapeshifted myself into a dwarf",
      "dwarven ale",
    ],
    facts: [
      "Canon: truly a giant, originally capable of appearing around fifty feet tall, but in the party he is shapeshifted into a dwarf.",
      "Canon: in giant form he wears leather armor, has a huge black beard reaching his chest, a big grin and a booming laugh.",
      "Canon: in Book 1 party scenes he struggles with short dwarf legs and keeps a compact dwarf-sized body.",
      "Canon: loves dwarven ale and has loud, boisterous tavern-fighter energy.",
      "Canon attitude: jovial, blunt, brave, physically fearless and protective, with comic confidence rather than refined heroism.",
      "Design choice: portrait should show his usual Book 1 dwarf form: very broad torso, massive hands, thick black beard, leather armor, heavy boots and ale-stained travel gear.",
      "Avoid: standard tall human, elegant noble dwarf, clean ceremonial armor, slim build or making him visually tiny and harmless.",
    ],
  },
  {
    id: "flower",
    name: "Flower",
    role: "Acrobat sharing a body with Illuna, also nicknamed Petal",
    kind: "little girl body shared with Illuna",
    anchors: [
      "golden amulet",
      "gray tank top shirt",
      "large pants commonly worn by clowns",
      "no shoes",
      "long red hair",
      "training in the room above",
    ],
    facts: [
      "Canon: shares the exact same small body with Illuna, also nicknamed Petal; do not create a separate Petal character.",
      "Canon: little girl body about four feet tall, looking no older than ten despite the character's unusual age and nature.",
      "Canon: long red hair almost to the waist, golden amulet around the neck, gray tank top shirt, oversized clown-like pants and bare feet.",
      "Canon: trains acrobatic movement in the ruins and is comfortable dropping from ceilings, flipping and moving fast.",
      "Canon attitude: cheerful, friendly, nervous when hiding secrets, energetic and expressive.",
      "Design choice: bright, agile reference pose with hands behind her back or ready to spring, but keep the full body visible and grounded.",
      "Avoid: adult proportions, shoes, armor, doll-like porcelain styling, separate Illuna body, or making the amulet optional.",
      "Distinction: Same body design as Illuna/Petal, but Flower uses a warm lively expression and normal child eyes instead of bright blue magical eyes.",
    ],
  },
  {
    id: "illuna",
    name: "Illuna (aka Petal)",
    role: "Banshee sharing Flower's body",
    kind: "banshee using Flower's body",
    anchors: [
      "eyes turn bright blue",
      "much colder tone than before",
      "Petal",
      "I've put Flower in a stasis",
      "golden cage",
    ],
    facts: [
      "Canon: Petal is Illuna's nickname, not a separate character; do not create a separate Petal portrait.",
      "Canon: same body as Flower: little girl proportions, long red hair, golden amulet, gray tank top shirt, oversized clown-like pants and bare feet.",
      "Canon: Illuna takes over with bright blue eyes, a much colder voice and an ancient, guarded expression.",
      "Canon: can place Flower in stasis, cast a golden cage and behave with far more calculation than Flower.",
      "Canon attitude: cold, stern, old-soul, protective when necessary, impatient with Flower's cheerful impulsiveness.",
      "Design choice: same pose and clothing silhouette as Flower, but colder posture, bright blue magical eyes and a faint blue-gold aura shift.",
      "Avoid: adult body, separate visible second girl, generic ghost, dark villain robes, red eyes or changing Flower's clothing.",
    ],
  },
  {
    id: "eiden",
    name: "Eiden",
    role: "Stillwater introduced before his name is known",
    kind: "human-looking stillwater young man",
    anchors: ["boy with his eyes closed", "hands in his pockets", "polite smile", "loose pants and a loose tunic", "late teens"],
    facts: [
      "Canon: human-looking boy or young man, late teens or no older than twenty when first seen.",
      "Canon: keeps his eyes closed, hands in his pockets and a polite smile, even during deadly confrontations.",
      "Canon: wears loose pants and a loose tunic, like casual sleep clothes, with no armor or protective gear.",
      "Canon: a stillwater with overwhelming power who looks harmless at first glance.",
      "Canon attitude: relaxed, unreadable, polite, bored by danger and quietly unsettling.",
      "Design choice: slightly messy just-woke-up presentation, soft casual fabric, bare minimum accessories and an effortless standing pose.",
      "Avoid: warrior armor, mage robes, weapons, glowing power display, angry expression, open eyes or heroic battle stance.",
    ],
  },
  {
    id: "arraka",
    name: "Arraka",
    role: "Ancient banshee trapped in an amulet",
    kind: "ancient banshee represented through an amulet",
    anchors: ["Arraka's amulet", "trapped in the amulet", "three different voices", "dark aura envelops Illuna", "pitch black"],
    facts: [
      "Canon: represented in Book 1 mainly through Flower's golden amulet, because Arraka is trapped inside it.",
      "Canon: her voice can sound like three women laughing or speaking simultaneously.",
      "Canon: malicious ancient banshee personality: sardonic, cruel, aggressive, knowledgeable and contemptuous.",
      "Canon: when her influence breaks through, dark aura and pitch-black eyes can appear on the shared body, but the portrait should not make her a normal separate human.",
      "Design choice: portray the golden amulet as the main subject, opened or cracked, with a spectral triple-female banshee presence and dark aura emerging from it.",
      "Avoid: ordinary necklace product shot, separate full human body, heroic ghost, friendly spirit, or replacing Flower/Illuna's shared body.",
    ],
  },
  {
    id: "tyrath",
    name: "Tyrath",
    role: "Dragon opponent",
    kind: "dragon",
    anchors: ["Tyrath", "dragon", "armored scales", "dragon's claw", "fire breath"],
    facts: [
      "Canon: A dragon, never a human portrait.",
      "Canon: massive, intelligent and physically threatening, with armored scales, dangerous claws and fire breath.",
      "Canon: old enemy of Eiden and strong enough to dominate a battlefield from the air.",
      "Canon attitude: predatory, proud, furious and tactical rather than animalistic only.",
      "Design choice: full-body dragon reference with visible wings, claws, tail, scale armor and internal fire glow in the throat.",
      "Avoid: humanoid dragonborn, cute dragon, saddle gear, knight armor, modern kaiju city scale or cropped dragon head only.",
    ],
  },
  {
    id: "cutthroat-dave",
    name: "Cutthroat Dave",
    role: "Bandit antagonist",
    kind: "human bandit leader",
    anchors: [
      "ordinary thug",
      "simple stained white shirt",
      "leather pants",
      "belt full of throwing knives",
      "untrimmed black beard",
      "flying knives",
    ],
    facts: [
      "Canon: ordinary thug and bandit leader, visually dirty, violent and overconfident rather than noble.",
      "Canon: wears a simple stained white shirt, leather pants and a belt full of throwing knives.",
      "Canon: has an untrimmed black beard, wicked smile and confident eyes.",
      "Canon: attacks with knives, including flying knives, and uses intimidation.",
      "Canon attitude: crude, vulgar, predatory and smug, the kind of roadside cutthroat people want to avoid.",
      "Design choice: rough boots, sweat-stained travel grime, cheap leather straps and knife-heavy silhouette.",
      "Avoid: noble duelist, clean assassin, elegant rogue, magical mage styling, heroic charm or ornate armor.",
    ],
  },
  {
    id: "azarius",
    name: "Azarius",
    role: "Sage of the West",
    kind: "elderly human sage wizard",
    anchors: [
      "fabled Azarius",
      "almost eighty years of age",
      "long beard as white as snow",
      "traditional wizard robes",
      "pointed hat",
      "gently stroking his white beard",
    ],
    facts: [
      "Canon: Azarius is the fabled Sage of the West, one of the four officially recognized elite sages.",
      "Canon: old human man, almost eighty years old, with a long white beard like snow.",
      "Canon: carries a long wooden staff in his right hand and wears traditional wizard robes with a pointed hat.",
      "Canon: his public face is famous enough that his portrait appears in Western Continent newspapers.",
      "Canon attitude: calm, authoritative, observant and powerful; he can stop a chaotic crowd through sheer status and threat.",
      "Design choice: classic but grounded wizard silhouette, travel-worn sage robes, carved wooden staff, wise tired eyes and composed posture.",
      "Avoid: red-robed fire mage styling; that belongs to Felran, not Azarius. Avoid young wizard, flashy battlemage armor or villain sorcerer treatment.",
    ],
  },
  {
    id: "diane",
    name: "Diane",
    role: "Kate's electrically powered friend",
    kind: "human-looking woman with electrical powers",
    anchors: [
      "rather muscular physique",
      "blue eyes",
      "short, blond hair",
      "tight leather pants",
      "gray tank top shirt",
      "burn scar on her left arm",
      "electrical currents",
    ],
    facts: [
      "Canon: woman close to Kate's age, with a rather muscular physique, blue eyes and short blond hair standing up from electrical power.",
      "Canon: wears tight leather pants and a gray tank top shirt.",
      "Canon: has a burn scar on her left arm, likely from hard fighting.",
      "Canon: no longer wears a collar when found in the sacred woods and can form electrical currents around herself.",
      "Canon attitude: tense, urgent, angry at Kate for returning, protective through harshness and ready to fight.",
      "Design choice: athletic stance, static electricity lifting hair, faint blue-white arcs around hands and scar, practical forest combat clothing.",
      "Avoid: lab-coat engineer styling, medieval noble dress, heavy armor, soft healer pose or generic lightning goddess costume.",
    ],
  },
  {
    id: "eleya",
    name: "Eleya, the golden fox",
    role: "Golden spirit fox ruler of the animal kingdom",
    kind: "golden spirit fox",
    anchors: ["Eleya, the golden fox", "great golden fox", "spirit fox", "insanely strong magical aura"],
    facts: [
      "Canon: Eleya is the golden fox and spirit fox who rules the animal kingdom in Book 1.",
      "Canon: her physical shape is that of a normal fox, with fur so bright it looks like actual gold.",
      "Canon: surrounded by an insanely strong golden magical aura, bright enough to be difficult to look at.",
      "Canon: her aura has an outworldly vibe similar to a banshee and she can create a golden cage.",
      "Canon attitude: regal, severe, rule-bound, merciless and accustomed to command.",
      "Design choice: natural fox anatomy, brilliant golden fur, hard intelligent eyes and controlled luminous aura around the body.",
      "Must be an animal fox, not a humanoid woman.",
      "Avoid: humanoid woman, kitsune girl, oversized monster fox, cute pet expression, armor or decorative jewelry overload.",
    ],
  },
  {
    id: "leo",
    name: "Leo",
    role: "Leopard follower",
    kind: "leopard",
    anchors: ["Leo the leopard", "leopard and a bull", "trusted lieutenants"],
    facts: [
      "Canon: Leo is a leopard follower of Eleya and one of the animal kingdom's trusted lieutenants.",
      "Canon: appears beside the spirit fox in the control room and should read as loyal guard presence.",
      "Canon attitude: alert, disciplined, intelligent and watchful.",
      "Design choice: natural leopard anatomy, tense low guard stance, sharp eyes and restrained fantasy aura only if needed.",
      "Avoid: humanoid leopard warrior, anthropomorphic body, armor, speech-bubble expression, cute pet pose or tiger markings; Leo must stay not anthropomorphic.",
    ],
  },
  {
    id: "taurus",
    name: "Taurus",
    role: "Bull lieutenant and bodyguard of Eleya",
    kind: "bull",
    anchors: ["Taurus the bull", "leopard and a bull", "trusted lieutenants", "furious look in his eyes"],
    facts: [
      "Canon: Taurus is the bull lieutenant of Eleya, the golden fox, paired with Leo the leopard as one of her trusted lieutenants.",
      "Canon: appears as an actual bull bodyguard walking at Eleya's side, not as a humanoid warrior.",
      "Canon: hears Daren's mockery and reacts with a furious look in his eyes, while staying disciplined beside Eleya.",
      "Canon attitude: loyal, protective, massive, easily irritated by disrespect and ready to guard Eleya.",
      "Design choice: natural bull anatomy, broad shoulders, heavy neck, strong horns, planted guard stance and stern intelligent eyes.",
      "Use an animal portrait, not a human portrait.",
      "Avoid: minotaur, humanoid bull-man, armor, weapon, cartoon farm animal, cute mascot or exaggerated monster proportions.",
    ],
  },
  {
    id: "golmyck",
    name: "Golmyck",
    role: "Gnome king of Thilias",
    kind: "gnome man",
    anchors: ["gnome with messy hair", "protection goggles", "oil-stained lab coat", "fiddling with some wires", "king of Thilias"],
    facts: [
      "Canon: gnome king of Thilias and renowned inventor, visually introduced in a workshop context.",
      "Canon: messy hair, protection goggles and oil-stained lab coat.",
      "Canon: fiddles with wires and mechanical work while humming cheerfully.",
      "Canon attitude: cheerful, eccentric, mechanically minded and oddly casual for a king.",
      "Design choice: short gnome proportions, oversized practical goggles, stained tools, wire coils, small mechanical parts and a confident inventor stance.",
      "Avoid: human-sized king, jeweled crown focus, clean royal robes, dark mad-scientist horror or medieval court portrait.",
    ],
  },
  {
    id: "suzie",
    name: "Suzie",
    role: "Rose's younger sister",
    kind: "eight-year-old human girl",
    anchors: ["Rose's eight year old sister", "virtual pet toy", "Billy's already fourteen years old", "tray full of muffins", "Suzie"],
    facts: [
      "Canon: Rose's eight-year-old sister from Thilias civilian life.",
      "Canon: carries or cares about a pocket virtual pet toy named Billy and speaks about it with childish pride.",
      "Canon: appears in a home context with muffins and family warmth.",
      "Canon attitude: earnest, proud, innocent and non-combatant.",
      "Design choice: modest town clothes, small hands holding a tray of muffins or the toy, curious expression and safe domestic posture.",
      "Avoid: combat gear, mage aura, adult proportions, royal child styling, horror-child mood or making the toy look like a modern smartphone.",
    ],
  },
  {
    id: "zack",
    name: "Zack",
    role: "Follower of the God of Death",
    kind: "human mage",
    anchors: ["Zack", "black robes and has a snake tattoo"],
    facts: [
      "Canon: mage in black robes with a snake tattoo on his bald head.",
      "Canon: follower of the God of Death, associated with necromancy and hostile religious certainty.",
      "Canon: uses accusatory language and treats opponents as heathens.",
      "Canon attitude: severe, fanatical, grim and confrontational.",
      "Design choice: gaunt posture, stark black robes, visible bald scalp tattoo, cold eyes and restrained death-magic atmosphere.",
      "Avoid: green-robed fate mage styling, friendly scholar, ornate noble robes, skull-mask villain excess or modern cultist clothing.",
    ],
  },
  {
    id: "elaria",
    name: "Elaria",
    role: "Talking deer mother",
    kind: "female deer",
    anchors: ["female deer and her fawn", "My name is Elaria", "front hooves", "This must all sound like weird animal noises"],
    facts: [
      "Canon: female deer and mother of Molan, able to speak an ancient language that humans hear as animal noises.",
      "Canon: cautious but polite enough to introduce herself and extend a front hoof for a handshake.",
      "Canon: seeks protection on the way back to her cave and reads Barry as non-threatening.",
      "Canon attitude: wary, dignified, maternal and intelligent.",
      "Design choice: natural doe anatomy, expressive eyes, subtle fantasy intelligence and forest-travel context.",
      "Use an animal portrait, not a human portrait.",
      "Avoid: humanoid deer woman, antlers on the doe, ornate spirit-fox aura, pet cartoon style or warrior gear.",
    ],
  },
  {
    id: "molan",
    name: "Molan",
    role: "Elaria's deer fawn",
    kind: "deer fawn",
    anchors: ["female deer and her fawn", "this is my child, Molan", "the fawn opens its mouth"],
    facts: [
      "Canon: Molan is Elaria's child and a deer fawn, not a fox.",
      "Canon: speaks an ancient language when Barry can understand him, while other humans would hear animal noises.",
      "Canon: young, vulnerable and dependent on Elaria during the forest encounter.",
      "Canon attitude: alert, timid, curious and childlike.",
      "Design choice: small natural fawn anatomy, slim legs, soft spotted coat and cautious stance close to forest cover.",
      "Use an animal portrait, not a human portrait.",
      "Avoid: fox design, humanoid child, adult stag antlers, spirit animal glow or cute cartoon exaggeration.",
    ],
  },
];

export const BOOK1_CHAPTERS = [
  {
    id: "ch1",
    label: "1",
    title: "Arrival and Cutthroat Dave",
    characters: ["barry", "daren", "cutthroat-dave"],
    scene: "A tense wilderness arrival on Varathia, with Barry and armored Daren facing the threat of Cutthroat Dave and his knives.",
  },
  {
    id: "ch2",
    label: "2",
    title: "Kate Appears",
    characters: ["barry", "daren", "kate"],
    scene: "Barry and Daren meet Kate in the forest at night, with uncertainty around her powerful magical aura.",
  },
  {
    id: "ch3",
    label: "3",
    title: "Varathian Wildlife",
    characters: ["barry", "daren", "kate", "elaria", "molan"],
    scene: "A cautious travel scene through Varathian wilderness where talking animals and old rules make the continent feel strange.",
  },
  {
    id: "ch4",
    label: "4",
    title: "Eiden and the Cutthroats",
    characters: ["barry", "daren", "kate", "eiden", "cutthroat-dave"],
    scene: "A forest confrontation where calm, closed-eyed Eiden faces violent cutthroats while Barry, Daren and Kate react.",
  },
  {
    id: "ch5",
    label: "5",
    title: "Rose and the Goblins",
    characters: ["barry", "daren", "kate", "rose"],
    scene: "Rose is rescued in the wilderness after a goblin encounter, with the party deciding whether to escort her.",
  },
  {
    id: "ch6",
    label: "6",
    title: "Tyrath",
    characters: ["barry", "daren", "kate", "rose", "tyrath"],
    scene: "A dramatic dragon fight against Tyrath, with Barry's stat device and the party under extreme pressure.",
  },
  {
    id: "ch7",
    label: "7",
    title: "Hadrik and Azarius",
    characters: ["barry", "daren", "kate", "rose", "hadrik", "azarius", "arraka", "diane", "zack"],
    scene: "A chaotic tournament conflict with Hadrik, Azarius, Arraka's amulet and traces of old lessathi secrets.",
  },
  {
    id: "ch8",
    label: "8",
    title: "The Animal Kingdom",
    characters: ["barry", "daren", "kate", "rose", "hadrik", "flower", "illuna", "eleya", "leo", "arraka"],
    scene: "The party is trapped in ancient ruins controlled by the animal kingdom, with Flower, Eleya and magical collars central to the image.",
  },
  {
    id: "ch9",
    label: "9",
    title: "Toward the Stronghold",
    characters: ["barry", "daren", "kate", "rose", "hadrik", "flower", "illuna"],
    scene: "The group crosses wild terrain toward the ogre stronghold while Flower and the others begin to bond.",
  },
  {
    id: "ch10",
    label: "10",
    title: "After the Ogres",
    characters: ["barry", "daren", "kate", "rose", "hadrik", "flower", "illuna", "eiden", "arraka"],
    scene: "A camp scene after the ogre conflict turns tense when Eiden appears and Flower's shared body reacts.",
  },
  {
    id: "ch11a",
    label: "11A",
    title: "Thilias",
    characters: ["barry", "daren", "kate", "rose", "hadrik", "flower", "illuna", "zack", "suzie"],
    scene: "The party reaches Thilias, moving from Rose's home life toward an ambush in the Beggar's district.",
  },
  {
    id: "ch11b",
    label: "11B",
    title: "The Announcement",
    characters: ["barry", "daren", "kate", "rose", "hadrik", "flower", "illuna", "arraka", "zack", "golmyck"],
    scene: "A market-square battle aftermath ends with giant holographic screens and Golmyck announcing the first tournament objectives.",
  },
];
