export const BOOK1_VISUAL_ROOT = "public/visuals/book1";

export const BOOK1_CHAPTER_IDS = [
  "ch1",
  "ch2",
  "ch3",
  "ch4",
  "ch5",
  "ch6",
  "ch7",
  "ch8",
  "ch9",
  "ch10",
  "ch11a",
  "ch11b",
];

export const BOOK1_CHARACTERS = [
  {
    id: "barry",
    name: "Barry",
    role: "Narrator and tournament participant",
    kind: "28-year-old ordinary human man from the Western Continent",
    anchors: [
      "ordinary guy",
      "my stat device",
      "stat booster",
      "strapped my crossbow to the back of my backpack",
      "my dagger",
      "my stat booster's screen",
      "backpack starts to glow",
      "since Daren enchanted it",
    ],
    facts: [
      "Canon: twenty-eight-year-old ordinary human man from the Western Continent, not visually heroic by default.",
      "Canon: practical traveler with a stat booster/stat device kept in his pocket; it has a small screen that can show stats, time, beeps and emergency prompts.",
      "Canon: carries a practical backpack that starts as ordinary, then Daren enchants it in chapter 6; after that it can hide contents and later display a magical inventory screen.",
      "Canon: straps a crossbow to the back of his backpack and carries a dagger for emergencies.",
      "Canon attitude: cautious, observant, self-deprecating and fallible, but determined enough to keep moving among much stronger mages.",
      "Design choice: average height and build, plain approachable face, short slightly messy dark brown hair, light stubble, tired but alert eyes.",
      "Design choice: practical worn travel clothing: simple off-white linen shirt, dark brown sleeveless leather vest or jerkin, sturdy dark trousers, leather belt and weathered travel boots.",
      "Design choice: show the stat booster as a palm-sized magical handheld device, similar in silhouette to a small virtual-pet toy or compact old digital organizer, with a small glowing screen showing abstract numeric rows and icons, no readable text.",
      "Design choice: show the backpack as weathered and outwardly ordinary by default; only moment prompts may request visible enchantment glow or a magical inventory screen.",
      "Avoid: heroic armor, mage robes, noble clothing, sinister sorcerer styling, modern phone design or superhero confidence.",
    ],
  },
  {
    id: "daren",
    name: "Daren",
    role: "Healer in armor",
    kind: "middle-aged human white mage in heavy armor",
    anchors: [
      "healer in armor",
      "heavy armor",
      "head is bald",
      "skin is dark",
      "mid forties",
      "scar on his forehead",
      "use a sword and a shield",
      "white light appear all around him",
      "legendary hero Daren",
    ],
    facts: [
      "Canon: famous white mage and healer known as the healer in armor and legendary savior of the Eastern Continent.",
      "Canon: dark-skinned human man, likely in his mid forties, bald, with an X-shaped scar on his forehead.",
      "Canon: wears heavy armor in combat; his shield and sword are central to his fighting style because he cannot rely on a normal shield spell against weapons.",
      "Canon: uses an enchanted sword and shield, white healing magic and protective barriers; his healing magic appears as bright white light.",
      "Canon attitude: confident, protective, brave and battle-ready, but still human enough to joke, get embarrassed and make mistakes.",
      "Design choice: full heavy adventurer armor with visible joints, dents and travel wear, practical rather than ceremonial.",
      "Design choice: broad, solid stance with sword and shield visible; white magical light should feel like healing/protection, not necromancy or dark sorcery.",
      "Avoid: young knight, hair, noble court armor, priest robes, grimdark villain styling, oversized fantasy spikes or angelic paladin excess.",
    ],
  },
  {
    id: "kate",
    name: "Kate",
    role: "Mage introduced before her name is known",
    kind: "early-twenties human ice mage",
    anchors: [
      "slim, tall figure",
      "long black hair",
      "long sleeved white blouse",
      "green, hooded cloak",
      "strong magical aura",
      "floating ice swords",
    ],
    facts: [
      "Canon: tall, slim human woman in her early twenties, with fair skin and long black hair.",
      "Canon: wears leather pants, a long-sleeved white blouse and a green hooded cloak.",
      "Canon: has a very serious look and a strong magical aura that makes others suspect she is far more dangerous than a normal mage.",
      "Canon: uses precise ice magic, including floating ice swords and ice barriers.",
      "Canon attitude: controlled, guarded, sharp and pragmatic; she should feel dangerous without looking theatrical.",
      "Design choice: fitted travel-worn clothing under the cloak, practical boots and a clean silhouette for fast movement.",
      "Avoid: soft court-dress styling, witch hat, bulky armor, seductive framing, fire magic or friendly tavern energy.",
    ],
  },
  {
    id: "rose",
    name: "Rose",
    role: "Varathian herbalist",
    kind: "mid-twenties human herbalist",
    anchors: ["long auburn hair", "light-brown eyes radiate kindness", "auburn dress", "herbalist", "bowing elegantly"],
    facts: [
      "Canon: beautiful Varathian herbalist in her mid twenties.",
      "Canon: long auburn hair, thin waist, soft feminine features, warm smile and light-brown eyes that radiate kindness.",
      "Canon: wears an auburn dress that matches her hair and bows elegantly when introduced.",
      "Canon: gathers rare herbs, treats sickness and belongs to civilian Thilias life rather than the tournament's warrior culture.",
      "Canon attitude: kind, polite, gentle and brave in a non-combatant way.",
      "Design choice: simple travel-ready herbalist details such as a small herb pouch, clean apron-like sash or modest satchel.",
      "Avoid: battle armor, mage robes, weapon-focused posing, royal gown, seductive framing or grim healer aesthetic.",
    ],
  },
  {
    id: "hadrik",
    name: "Hadrik",
    role: "Giant shapeshifted as a dwarf",
    kind: "giant man shapeshifted into a dwarf",
    anchors: [
      "dressed in leather armor",
      "black beard that reaches down to his chest",
      "big grin",
      "shapeshifted myself into a dwarf",
      "dwarven ale",
    ],
    facts: [
      "Canon: truly a giant, originally capable of appearing around fifty feet tall, but in the party he is shapeshifted into a dwarf.",
      "Canon: in giant form he wears leather armor, has a huge black beard reaching his chest, a big grin and a booming laugh.",
      "Canon: in Book 1 party scenes he struggles with short dwarf legs and keeps a compact dwarf-sized body.",
      "Canon: loves dwarven ale and has loud, boisterous tavern-fighter energy.",
      "Canon attitude: jovial, blunt, brave, physically fearless and protective, with comic confidence rather than refined heroism.",
      "Design choice: portrait should show his usual Book 1 dwarf form: very broad torso, massive hands, thick black beard, leather armor, heavy boots and ale-stained travel gear.",
      "Avoid: standard tall human, elegant noble dwarf, clean ceremonial armor, slim build or making him visually tiny and harmless.",
    ],
  },
  {
    id: "flower",
    name: "Flower",
    role: "Acrobat sharing a body with Illuna, also nicknamed Petal",
    kind: "little girl body shared with Illuna",
    anchors: [
      "golden amulet",
      "gray tank top shirt",
      "large pants commonly worn by clowns",
      "no shoes",
      "long red hair",
      "training in the room above",
    ],
    facts: [
      "Canon: shares the exact same small body with Illuna, also nicknamed Petal; do not create a separate Petal character.",
      "Canon: little girl body about four feet tall, looking no older than ten despite the character's unusual age and nature.",
      "Canon: long red hair almost to the waist, golden amulet around the neck, gray tank top shirt, oversized clown-like pants and bare feet.",
      "Canon: trains acrobatic movement in the ruins and is comfortable dropping from ceilings, flipping and moving fast.",
      "Canon attitude: cheerful, friendly, nervous when hiding secrets, energetic and expressive.",
      "Design choice: bright, agile reference pose with hands behind her back or ready to spring, but keep the full body visible and grounded.",
      "Avoid: adult proportions, shoes, armor, doll-like porcelain styling, separate Illuna body, or making the amulet optional.",
      "Distinction: Same body design as Illuna/Petal, but Flower uses a warm lively expression and normal child eyes instead of bright blue magical eyes.",
    ],
  },
  {
    id: "illuna",
    name: "Illuna (aka Petal)",
    role: "Banshee sharing Flower's body",
    kind: "banshee using Flower's body",
    anchors: [
      "eyes turn bright blue",
      "much colder tone than before",
      "Petal",
      "I've put Flower in a stasis",
      "golden cage",
    ],
    facts: [
      "Canon: Petal is Illuna's nickname, not a separate character; do not create a separate Petal portrait.",
      "Canon: same body as Flower: little girl proportions, long red hair, golden amulet, gray tank top shirt, oversized clown-like pants and bare feet.",
      "Canon: Illuna takes over with bright blue eyes, a much colder voice and an ancient, guarded expression.",
      "Canon: can place Flower in stasis, cast a golden cage and behave with far more calculation than Flower.",
      "Canon attitude: cold, stern, old-soul, protective when necessary, impatient with Flower's cheerful impulsiveness.",
      "Design choice: same pose and clothing silhouette as Flower, but colder posture, bright blue magical eyes and a faint blue-gold aura shift.",
      "Avoid: adult body, separate visible second girl, generic ghost, dark villain robes, red eyes or changing Flower's clothing.",
    ],
  },
  {
    id: "eiden",
    name: "Eiden",
    role: "Stillwater introduced before his name is known",
    kind: "human-looking stillwater young man",
    anchors: ["boy with his eyes closed", "hands in his pockets", "polite smile", "loose pants and a loose tunic", "late teens"],
    facts: [
      "Canon: human-looking boy or young man, late teens or no older than twenty when first seen.",
      "Canon: keeps his eyes closed, hands in his pockets and a polite smile, even during deadly confrontations.",
      "Canon: wears loose pants and a loose tunic, like casual sleep clothes, with no armor or protective gear.",
      "Canon: a stillwater with overwhelming power who looks harmless at first glance.",
      "Canon attitude: relaxed, unreadable, polite, bored by danger and quietly unsettling.",
      "Design choice: slightly messy just-woke-up presentation, soft casual fabric, bare minimum accessories and an effortless standing pose.",
      "Avoid: warrior armor, mage robes, weapons, glowing power display, angry expression, open eyes or heroic battle stance.",
    ],
  },
  {
    id: "arraka",
    name: "Arraka",
    role: "Ancient banshee trapped in an amulet",
    kind: "ancient banshee represented through an amulet",
    anchors: ["Arraka's amulet", "trapped in the amulet", "three different voices", "dark aura envelops Illuna", "pitch black"],
    facts: [
      "Canon: represented in Book 1 mainly through Flower's golden amulet, because Arraka is trapped inside it.",
      "Canon: her voice can sound like three women laughing or speaking simultaneously.",
      "Canon: malicious ancient banshee personality: sardonic, cruel, aggressive, knowledgeable and contemptuous.",
      "Canon: when her influence breaks through, dark aura and pitch-black eyes can appear on the shared body, but the portrait should not make her a normal separate human.",
      "Design choice: portray the golden amulet as the main subject, opened or cracked, with a spectral triple-female banshee presence and dark aura emerging from it.",
      "Avoid: ordinary necklace product shot, separate full human body, heroic ghost, friendly spirit, or replacing Flower/Illuna's shared body.",
    ],
  },
  {
    id: "tyrath",
    name: "Tyrath",
    role: "Dragon opponent",
    kind: "dragon",
    anchors: ["Tyrath", "dragon", "armored scales", "dragon's claw", "fire breath"],
    facts: [
      "Canon: A dragon, never a human portrait.",
      "Canon: massive, intelligent and physically threatening, with armored scales, dangerous claws and fire breath.",
      "Canon: old enemy of Eiden and strong enough to dominate a battlefield from the air.",
      "Canon attitude: predatory, proud, furious and tactical rather than animalistic only.",
      "Design choice: full-body dragon reference with visible wings, claws, tail, scale armor and internal fire glow in the throat.",
      "Avoid: humanoid dragonborn, cute dragon, saddle gear, knight armor, modern kaiju city scale or cropped dragon head only.",
    ],
  },
  {
    id: "cutthroat-dave",
    name: "Cutthroat Dave",
    role: "Bandit antagonist",
    kind: "human bandit leader",
    anchors: [
      "ordinary thug",
      "simple stained white shirt",
      "leather pants",
      "belt full of throwing knives",
      "untrimmed black beard",
      "flying knives",
    ],
    facts: [
      "Canon: ordinary thug and bandit leader, visually dirty, violent and overconfident rather than noble.",
      "Canon: wears a simple stained white shirt, leather pants and a belt full of throwing knives.",
      "Canon: has an untrimmed black beard, wicked smile and confident eyes.",
      "Canon: attacks with knives, including flying knives, and uses intimidation.",
      "Canon attitude: crude, vulgar, predatory and smug, the kind of roadside cutthroat people want to avoid.",
      "Design choice: rough boots, sweat-stained travel grime, cheap leather straps and knife-heavy silhouette.",
      "Avoid: noble duelist, clean assassin, elegant rogue, magical mage styling, heroic charm or ornate armor.",
    ],
  },
  {
    id: "azarius",
    name: "Azarius",
    role: "Sage of the West",
    kind: "elderly human sage wizard",
    anchors: [
      "fabled Azarius",
      "almost eighty years of age",
      "long beard as white as snow",
      "traditional wizard robes",
      "pointed hat",
      "gently stroking his white beard",
    ],
    facts: [
      "Canon: Azarius is the fabled Sage of the West, one of the four officially recognized elite sages.",
      "Canon: old human man, almost eighty years old, with a long white beard like snow.",
      "Canon: carries a long wooden staff in his right hand and wears traditional wizard robes with a pointed hat.",
      "Canon: his public face is famous enough that his portrait appears in Western Continent newspapers.",
      "Canon attitude: calm, authoritative, observant and powerful; he can stop a chaotic crowd through sheer status and threat.",
      "Design choice: classic but grounded wizard silhouette, travel-worn sage robes, carved wooden staff, wise tired eyes and composed posture.",
      "Avoid: red-robed fire mage styling; that belongs to Felran, not Azarius. Avoid young wizard, flashy battlemage armor or villain sorcerer treatment.",
    ],
  },
  {
    id: "diane",
    name: "Diane",
    role: "Kate's electrically powered friend",
    kind: "human-looking woman with electrical powers",
    anchors: [
      "rather muscular physique",
      "blue eyes",
      "short, blond hair",
      "tight leather pants",
      "gray tank top shirt",
      "burn scar on her left arm",
      "electrical currents",
    ],
    facts: [
      "Canon: woman close to Kate's age, with a rather muscular physique, blue eyes and short blond hair standing up from electrical power.",
      "Canon: wears tight leather pants and a gray tank top shirt.",
      "Canon: has a burn scar on her left arm, likely from hard fighting.",
      "Canon: no longer wears a collar when found in the sacred woods and can form electrical currents around herself.",
      "Canon attitude: tense, urgent, angry at Kate for returning, protective through harshness and ready to fight.",
      "Design choice: athletic stance, static electricity lifting hair, faint blue-white arcs around hands and scar, practical forest combat clothing.",
      "Avoid: lab-coat engineer styling, medieval noble dress, heavy armor, soft healer pose or generic lightning goddess costume.",
    ],
  },
  {
    id: "eleya",
    name: "Eleya, the golden fox",
    role: "Golden spirit fox ruler of the animal kingdom",
    kind: "golden spirit fox",
    anchors: ["Eleya, the golden fox", "great golden fox", "spirit fox", "insanely strong magical aura"],
    facts: [
      "Canon: Eleya is the golden fox and spirit fox who rules the animal kingdom in Book 1.",
      "Canon: her physical shape is that of a normal fox, with fur so bright it looks like actual gold.",
      "Canon: surrounded by an insanely strong golden magical aura, bright enough to be difficult to look at.",
      "Canon: her aura has an outworldly vibe similar to a banshee and she can create a golden cage.",
      "Canon attitude: regal, severe, rule-bound, merciless and accustomed to command.",
      "Design choice: natural fox anatomy, brilliant golden fur, hard intelligent eyes and controlled luminous aura around the body.",
      "Must be an animal fox, not a humanoid woman.",
      "Avoid: humanoid woman, kitsune girl, oversized monster fox, cute pet expression, armor or decorative jewelry overload.",
    ],
  },
  {
    id: "leo",
    name: "Leo",
    role: "Leopard follower",
    kind: "leopard",
    anchors: ["Leo the leopard", "leopard and a bull", "trusted lieutenants"],
    facts: [
      "Canon: Leo is a leopard follower of Eleya and one of the animal kingdom's trusted lieutenants.",
      "Canon: appears beside the spirit fox in the control room and should read as loyal guard presence.",
      "Canon attitude: alert, disciplined, intelligent and watchful.",
      "Design choice: natural leopard anatomy, tense low guard stance, sharp eyes and restrained fantasy aura only if needed.",
      "Avoid: humanoid leopard warrior, anthropomorphic body, armor, speech-bubble expression, cute pet pose or tiger markings; Leo must stay not anthropomorphic.",
    ],
  },
  {
    id: "taurus",
    name: "Taurus",
    role: "Bull lieutenant and bodyguard of Eleya",
    kind: "bull",
    anchors: ["Taurus the bull", "leopard and a bull", "trusted lieutenants", "furious look in his eyes"],
    facts: [
      "Canon: Taurus is the bull lieutenant of Eleya, the golden fox, paired with Leo the leopard as one of her trusted lieutenants.",
      "Canon: appears as an actual bull bodyguard walking at Eleya's side, not as a humanoid warrior.",
      "Canon: hears Daren's mockery and reacts with a furious look in his eyes, while staying disciplined beside Eleya.",
      "Canon attitude: loyal, protective, massive, easily irritated by disrespect and ready to guard Eleya.",
      "Design choice: natural bull anatomy, broad shoulders, heavy neck, strong horns, planted guard stance and stern intelligent eyes.",
      "Use an animal portrait, not a human portrait.",
      "Avoid: minotaur, humanoid bull-man, armor, weapon, cartoon farm animal, cute mascot or exaggerated monster proportions.",
    ],
  },
  {
    id: "golmyck",
    name: "Golmyck",
    role: "Gnome king of Thilias",
    kind: "gnome man",
    anchors: ["gnome with messy hair", "protection goggles", "oil-stained lab coat", "fiddling with some wires", "king of Thilias"],
    facts: [
      "Canon: gnome king of Thilias and renowned inventor, visually introduced in a workshop context.",
      "Canon: messy hair, protection goggles and oil-stained lab coat.",
      "Canon: fiddles with wires and mechanical work while humming cheerfully.",
      "Canon attitude: cheerful, eccentric, mechanically minded and oddly casual for a king.",
      "Design choice: short gnome proportions, oversized practical goggles, stained tools, wire coils, small mechanical parts and a confident inventor stance.",
      "Avoid: human-sized king, jeweled crown focus, clean royal robes, dark mad-scientist horror or medieval court portrait.",
    ],
  },
  {
    id: "suzie",
    name: "Suzie",
    role: "Rose's younger sister",
    kind: "eight-year-old human girl",
    anchors: ["Rose's eight year old sister", "virtual pet toy", "Billy's already fourteen years old", "tray full of muffins", "Suzie"],
    facts: [
      "Canon: Rose's eight-year-old sister from Thilias civilian life.",
      "Canon: carries or cares about a pocket virtual pet toy named Billy and speaks about it with childish pride.",
      "Canon: appears in a home context with muffins and family warmth.",
      "Canon attitude: earnest, proud, innocent and non-combatant.",
      "Design choice: modest town clothes, small hands holding a tray of muffins or the toy, curious expression and safe domestic posture.",
      "Avoid: combat gear, mage aura, adult proportions, royal child styling, horror-child mood or making the toy look like a modern smartphone.",
    ],
  },
  {
    id: "zack",
    name: "Zack",
    role: "Follower of the God of Death",
    kind: "human mage",
    anchors: ["Zack", "black robes and has a snake tattoo"],
    facts: [
      "Canon: mage in black robes with a snake tattoo on his bald head.",
      "Canon: follower of the God of Death, associated with necromancy and hostile religious certainty.",
      "Canon: uses accusatory language and treats opponents as heathens.",
      "Canon attitude: severe, fanatical, grim and confrontational.",
      "Design choice: gaunt posture, stark black robes, visible bald scalp tattoo, cold eyes and restrained death-magic atmosphere.",
      "Avoid: green-robed fate mage styling, friendly scholar, ornate noble robes, skull-mask villain excess or modern cultist clothing.",
    ],
  },
  {
    id: "elaria",
    name: "Elaria",
    role: "Talking deer mother",
    kind: "female deer",
    anchors: ["female deer and her fawn", "My name is Elaria", "front hooves", "This must all sound like weird animal noises"],
    facts: [
      "Canon: female deer and mother of Molan, able to speak an ancient language that humans hear as animal noises.",
      "Canon: cautious but polite enough to introduce herself and extend a front hoof for a handshake.",
      "Canon: seeks protection on the way back to her cave and reads Barry as non-threatening.",
      "Canon attitude: wary, dignified, maternal and intelligent.",
      "Design choice: natural doe anatomy, expressive eyes, subtle fantasy intelligence and forest-travel context.",
      "Use an animal portrait, not a human portrait.",
      "Avoid: humanoid deer woman, antlers on the doe, ornate spirit-fox aura, pet cartoon style or warrior gear.",
    ],
  },
  {
    id: "molan",
    name: "Molan",
    role: "Elaria's deer fawn",
    kind: "deer fawn",
    anchors: ["female deer and her fawn", "this is my child, Molan", "the fawn opens its mouth"],
    facts: [
      "Canon: Molan is Elaria's child and a deer fawn, not a fox.",
      "Canon: speaks an ancient language when Barry can understand him, while other humans would hear animal noises.",
      "Canon: young, vulnerable and dependent on Elaria during the forest encounter.",
      "Canon attitude: alert, timid, curious and childlike.",
      "Design choice: small natural fawn anatomy, slim legs, soft spotted coat and cautious stance close to forest cover.",
      "Use an animal portrait, not a human portrait.",
      "Avoid: fox design, humanoid child, adult stag antlers, spirit animal glow or cute cartoon exaggeration.",
    ],
  },
];

export const BOOK1_MOMENTS = [
  {
    id: "ch1-forest-arrival",
    chapterId: "ch1",
    triggerSceneId: "Ch1-Intro2",
    title: "Barry arrives in Varathia",
    characters: ["barry"],
    settingFacts: [
      "Ordinary dense Varathian forest near the tournament starting area, with undergrowth, tall trunks, mossy roots and a nearby clearing.",
      "The danger comes from distant explosions and nearby tournament fights, not from a cursed or hostile-looking forest.",
    ],
    actionFacts: [
      "Barry has just arrived, tense and excited, listening for threats while trying not to look heroic.",
      "Show him alone and slightly overwhelmed, using body language more than spectacle.",
    ],
    materialDetails: [
      "Barry's backpack is still ordinary-looking here, with no visible crossbow strapped to it.",
      "His stat device stays tucked away; this first-arrival image should not put it in his hand.",
    ],
    unnamedCharacters: [],
    composition: ["Wide 16:9 landscape, Barry full body but small enough for the forest scale to matter, readable on mobile."],
    timelineOverrides: ["Use Barry's portrait for identity, clothing and body type, but remove the crossbow completely for this early Book 1 moment."],
    pathCompatibility: ["This scene follows Excited, Calm or Afraid intro choices, so Barry's expression must stay broadly alert and overwhelmed rather than locked to one emotion."],
    avoid: ["No Daren, no Kate, no monsters, no city, no heroic pose, no crossbow."],
  },
  {
    id: "ch1-cutthroat-dave",
    chapterId: "ch1",
    triggerSceneId: "Ch1-Cutthroat Dave",
    title: "Dave confronts Barry while defeated Daren stands nearby",
    characters: ["barry", "cutthroat-dave", "daren"],
    settingFacts: ["Same wild forest clearing, close trees, rough bark, low branches and tense hiding-space near Barry."],
    actionFacts: [
      "Cutthroat Dave threatens Barry with magical throwing knives while Barry is at the clearing edge or near a tree, cautious and trying to survive.",
      "Daren is visibly nearby, defeated and weakened in heavy armor, with his shield on the ground and his sword barely held.",
      "Dave should look crude, dirty and overconfident, not elegant or noble.",
    ],
    materialDetails: [
      "Show Dave's stained shirt, leather pants, belt full of throwing knives and rough bandit gear.",
      "Barry has only his ordinary backpack, with the stat device kept in a pocket; no crossbow yet.",
      "Daren's armor should look heavy and travel-worn; his posture should read exhausted and temporarily beaten, not dead.",
    ],
    unnamedCharacters: ["Optional distant bandit silhouettes only if needed for depth; keep focus on Dave, Barry and defeated Daren."],
    composition: ["Medium-wide 16:9 scene, Dave as the aggressive center, Barry tense at the edge, Daren weakened to the side with shield on the ground."],
    timelineOverrides: ["Use Barry reference without crossbow; keep him ordinary, frightened and hurt rather than action-heroic."],
    pathCompatibility: ["This scene has three route variants: Barry may stay hidden, step out, or answer from cover. Do not make a shoulder-pinning wound or Barry fully exposed the only possible reading."],
    avoid: ["No gore focus, no heroic armor, no crossbow on Barry, no Daren hidden or absent, no mandatory shoulder wound as the focal action."],
  },
  {
    id: "ch2-kate-appears",
    chapterId: "ch2",
    triggerSceneId: "Ch2-Intro",
    title: "Kate appears behind Barry and Daren",
    characters: ["barry", "daren", "kate"],
    settingFacts: [
      "Ordinary Varathian forest clearing near the tournament start: natural trees, leaf litter, open ground and simple woodland depth.",
      "Use neutral natural forest light; do not make the environment look hostile, cursed, black, foggy or horror-like.",
    ],
    actionFacts: [
      "Barry and Daren turn toward Kate, who stands behind them with serious controlled posture.",
      "Kate's strong magical aura should feel dangerous and uncertain through her posture and the subtle air around her, not through a darkened environment.",
    ],
    materialDetails: [
      "Kate wears leather pants, a long-sleeved white blouse and green hooded cloak; Daren is in heavy armor with sword and shield.",
      "Barry still has no crossbow.",
    ],
    unnamedCharacters: [],
    composition: ["Wide 16:9, Kate as the focal silhouette, Barry and Daren reacting in foreground or side profile."],
    timelineOverrides: ["Use Barry reference without crossbow; use Kate reference for identity but make this a serious, controlled first-appearance pose."],
    avoid: [
      "No fire magic, no friendly tavern lighting, no revealed banshee form, no crossbow on Barry.",
      "No dark fantasy forest, no black trunks, no horror fog, no ominous mist, no cursed woodland palette.",
    ],
  },
  {
    id: "ch2-mage-ambush",
    chapterId: "ch2",
    triggerSceneId: "Ch2-Battle-begins",
    title: "Kate shows real magic",
    characters: ["barry", "daren", "kate"],
    settingFacts: ["Forest battlefield with fallen trees, churned dirt, freezing air and scattered hostile tournament mages."],
    actionFacts: [
      "Kate confronts backstabbers and sword throwers while the air grows colder around her.",
      "Daren protects the group, Barry watches from a weaker survival position.",
    ],
    materialDetails: [
      "Ice swords or jagged ice formations should appear around Kate, precise and dangerous.",
      "Hostile mages are anonymous, practical tournament fighters with axes, thrown swords and mixed travel gear.",
    ],
    unnamedCharacters: ["Battleaxe mage, sword thrower and a few hostile mages; they should be human tournament participants, not monsters."],
    composition: ["Cinematic 16:9 action scene, Kate centered with ice magic, Daren shield-side, Barry smaller and vulnerable."],
    timelineOverrides: ["Barry still has no crossbow; do not use the later backpack-crossbow silhouette."],
    avoid: ["No fire aura for Kate, no superhero ice costume, no gore, no crossbow on Barry."],
  },
  {
    id: "ch2-elaria-molan",
    chapterId: "ch2",
    triggerSceneId: "Ch2-Deer",
    title: "Elaria and Molan at the forest edge",
    characters: ["barry", "daren", "kate", "elaria", "molan"],
    settingFacts: ["Ordinary Varathian forest edge near the path toward the mountains, with trees, undergrowth, animal tracks and natural woodland depth."],
    actionFacts: ["Elaria the doe and Molan the fawn cautiously approach the travelers, intelligent but still fully animal."],
    materialDetails: ["Elaria and Molan must use natural deer anatomy; no humanoid animal design."],
    unnamedCharacters: [],
    composition: ["Wide calm 16:9, humans low and non-threatening, deer and fawn near forest cover."],
    timelineOverrides: ["Barry still has no crossbow; keep the animals natural and consistent with their portraits."],
    pathCompatibility: ["The player may or may not understand the deer language here, so show a cautious animal encounter rather than readable dialogue or explicit translation."],
    avoid: ["No talking bubble, no humanoid deer people, no spirit fox aura, no crossbow on Barry."],
  },
  {
    id: "ch3-cave-meal",
    chapterId: "ch3",
    triggerSceneId: "Ch3-Plate",
    title: "Meal inside Elaria's cave",
    characters: ["barry", "daren", "kate", "elaria", "molan"],
    settingFacts: [
      "Small natural cave used by Elaria and Molan, rough stone walls, roots near the entrance and modest shelter details.",
      "Use simple low cave light and a sheltered, quiet mood; do not make the surrounding forest look artificially hostile.",
    ],
    actionFacts: ["Barry, Daren and Kate share a strange peaceful meal with the intelligent deer and fawn."],
    materialDetails: ["Simple plates or conjured food may appear, but keep props rustic and not luxurious."],
    unnamedCharacters: [],
    composition: ["16:9 interior cave scene, characters arranged around food with animals still anatomically natural."],
    timelineOverrides: ["Barry still has no crossbow."],
    avoid: ["No tavern, no castle banquet, no humanoid deer, no crossbow on Barry."],
  },
  {
    id: "ch3-crossbow-ambush",
    chapterId: "ch3",
    triggerSceneId: "Ch3-Dart",
    title: "The hidden crossbowmen strike",
    characters: ["barry", "daren", "kate"],
    settingFacts: ["Forest ambush zone with distant trees used for cover, hidden attackers and sudden projectiles cutting through the air."],
    actionFacts: [
      "Anonymous crossbowmen attack from hiding while the party reacts under pressure.",
      "Barry is still before owning his own crossbow; any crossbows belong to the attackers.",
    ],
    materialDetails: [
      "Attackers use practical crossbows, leather straps, simple dark travel clothes and cover positions.",
      "Kate and Daren should look ready to shield or counterattack.",
    ],
    unnamedCharacters: ["Several hidden human crossbowmen, practical and dirty, not uniform soldiers."],
    composition: ["16:9 action scene with visible projectile lines, forest cover and the party caught between angles."],
    timelineOverrides: ["Do not show Barry carrying or using his own crossbow yet."],
    pathCompatibility: ["The player's perception/hearing/premonition can change how early the ambush is noticed, so show the ambush and party reaction without implying a specific stat-check outcome."],
    avoid: ["No later Barry crossbow, no gunpowder weapons, no city walls, no gore focus."],
  },
  {
    id: "ch3-kate-ice-defense",
    chapterId: "ch3",
    triggerSceneId: "Ch3-Ice-hand",
    title: "Kate's ice defense",
    characters: ["barry", "daren", "kate"],
    settingFacts: ["Same forest battle zone with smoke from the ambush and precise ice magic cutting through the trees."],
    actionFacts: ["Kate uses controlled ice magic to stop the ambush while Barry and Daren reposition."],
    materialDetails: ["Ice hands, ice barriers or floating ice weapons should feel precise and lethal, not decorative."],
    unnamedCharacters: ["Retreating or trapped crossbowmen in the background, partially obscured by ice and trees."],
    composition: ["Kate foreground focal point, Barry and Daren secondary, 16:9 with clear ice silhouette."],
    timelineOverrides: ["Barry still has no crossbow."],
    avoid: ["No fire magic, no glittery fairy ice, no crossbow on Barry."],
  },
  {
    id: "ch3-barry-tree-lift",
    chapterId: "ch3",
    triggerSceneId: "Ch3-Lift",
    title: "Barry faces the fallen tree tactic",
    characters: ["barry"],
    settingFacts: ["Damaged forest battle site with a large fallen tree, broken branches, torn ground and scattered leaves."],
    actionFacts: ["Barry stands beside the fallen tree during a tactical crisis, considering or attempting a desperate stat-boosted move without the image proving whether he succeeds."],
    materialDetails: ["Do not put Barry's stat device in his hand here; communicate the desperate stat-boost attempt through posture, strain and the fallen tree, while the backpack remains ordinary and without crossbow."],
    unnamedCharacters: ["Optional blurred hostile figures at the edge, but the focus is Barry and the tree."],
    composition: ["Wide low-angle 16:9, full-body Barry dwarfed by the tree's scale, readable without making him look naturally superhuman."],
    timelineOverrides: ["Barry has no crossbow here; any strength attempt should feel temporary and device-driven, not his normal heroic strength."],
    pathCompatibility: ["This scene includes success, failure and not-trying variants, so do not show the tree already lifted high or the outcome resolved."],
    avoid: ["No permanent muscle transformation, no superhero pose, no crossbow on Barry, no guaranteed successful tree lift."],
  },
  {
    id: "ch4-eiden-arrival",
    chapterId: "ch4",
    triggerSceneId: "Ch4-Intro2",
    title: "Eiden arrives with eyes closed",
    characters: ["barry", "daren", "kate", "eiden"],
    settingFacts: ["Forest confrontation aftermath, tense clearing with cutthroat danger nearby and unnatural calm around Eiden."],
    actionFacts: ["Eiden stands relaxed with eyes closed and hands in pockets while the others react to his impossible confidence."],
    materialDetails: ["Eiden wears loose pants and loose tunic, no armor, no weapons, no visible spellcasting flourish."],
    unnamedCharacters: [],
    composition: ["16:9 scene, Eiden casually centered or offset, party watching him with suspicion."],
    timelineOverrides: ["Barry still has no crossbow."],
    pathCompatibility: ["The player can arrive with different stated objectives, so focus on Eiden's first unsettling presence rather than Barry's exact explanation."],
    avoid: ["No glowing battle aura on Eiden, no open eyes, no mage robe, no crossbow on Barry."],
  },
  {
    id: "ch4-dave-vs-eiden",
    chapterId: "ch4",
    triggerSceneId: "Ch4-Dave-vs-Eiden",
    title: "Dave threatens Eiden",
    characters: ["eiden", "cutthroat-dave"],
    settingFacts: ["Forest clearing with bandit tension, knife threat and unnerving stillness."],
    actionFacts: ["Cutthroat Dave postures with knives while Eiden remains relaxed, eyes closed, hands in pockets."],
    materialDetails: ["Dave's stained shirt and throwing-knife belt should contrast Eiden's loose sleep-like clothes."],
    unnamedCharacters: ["Optional cutthroat silhouettes behind Dave, rough and poorly coordinated."],
    composition: ["16:9 standoff with Dave aggressive in foreground and Eiden calm as the impossible focal point."],
    timelineOverrides: [],
    avoid: ["No open-eyed Eiden, no armor on Eiden, no noble assassin styling for Dave, no gore."],
  },
  {
    id: "ch4-barry-vs-dave",
    chapterId: "ch4",
    triggerSceneId: "Ch4-Barry-vs-Dave",
    title: "Barry faces Cutthroat Dave",
    characters: ["barry", "kate", "cutthroat-dave"],
    settingFacts: ["Forest fight space with trees close enough for cover, dirty ground and the aftermath of earlier knife violence."],
    actionFacts: ["Barry confronts Dave while Kate's dangerous presence or ice magic shifts the balance."],
    materialDetails: ["Barry has ordinary travel gear only; Dave's knives and rough clothes remain central."],
    unnamedCharacters: [],
    composition: ["16:9 confrontation, Barry visibly scared but determined, Dave threatening, Kate as cold controlled pressure."],
    timelineOverrides: ["Barry still has no crossbow; keep him under-equipped and fallible."],
    pathCompatibility: ["Barry and Kate's exact injury state depends on previous choices, so keep wounds subtle and non-specific."],
    avoid: ["No heroic armor for Barry, no later crossbow, no excessive gore."],
  },
  {
    id: "ch5-wake-kate",
    chapterId: "ch5",
    triggerSceneId: "Ch5-Wake-Kate",
    title: "Aftermath with Kate",
    characters: ["barry", "daren", "kate"],
    settingFacts: ["Quiet wilderness or cave-side recovery area after the cutthroat/Eiden crisis, with simple natural stillness and no visible enemy threat."],
    actionFacts: ["The party regroups emotionally; Kate should look guarded and serious, Barry cautious, Daren protective."],
    materialDetails: ["Simple travel gear, no dramatic enemy presence, subtle signs of recent exhaustion."],
    unnamedCharacters: [],
    composition: ["Restrained 16:9 character scene with tension in posture rather than action."],
    timelineOverrides: ["Barry still has no crossbow."],
    pathCompatibility: ["Barry and Kate may have different injury states from chapter 3, so show fatigue and guarded recovery without route-specific wounds."],
    avoid: ["No celebratory campfire party, no crossbow on Barry, no city."],
  },
  {
    id: "ch5-rose-scream",
    chapterId: "ch5",
    triggerSceneId: "Ch5-Scream",
    title: "A distant scream interrupts the party",
    characters: ["barry", "daren", "kate"],
    settingFacts: ["Forest path or cave-side wilderness with the party hearing a woman's scream from far away; the source is not directly visible yet."],
    actionFacts: ["Barry reacts to the warning message and the distant scream while Daren and Kate look toward the unseen danger."],
    materialDetails: ["Do not identify Rose visually in this moment; the local woman has not been seen clearly yet."],
    unnamedCharacters: ["Optional tiny, unreadable movement deep between trees, but no clear victim portrait and no close monster reveal."],
    composition: ["16:9 depth composition: party foreground, empty forest direction in the distance, tension carried by posture and attention."],
    timelineOverrides: ["Barry still has no crossbow."],
    pathCompatibility: ["This scene can follow different private-conversation choices, so focus on the shared interruption: the scream, the warning and distant danger."],
    avoid: ["No close heroic rescue pose yet, no visible Rose portrait, no large ogres, no crossbow on Barry."],
  },
  {
    id: "ch5-goblin-rescue",
    chapterId: "ch5",
    triggerSceneId: "Ch5-Goblins2",
    title: "The goblins and Rose",
    characters: ["barry", "daren", "kate", "rose"],
    settingFacts: ["Forest encounter zone with scrub, rocks and a small rough clearing where goblins block Rose's path."],
    actionFacts: ["Barry, Rose, Daren and Kate face the goblins in a tense negotiation or confrontation without resolving the exact tactic visually."],
    materialDetails: ["Goblins are small, opportunistic, dirty fantasy creatures with crude gear, not comic mascots."],
    unnamedCharacters: ["Small goblin group with a nervous leader, crude bags and improvised weapons."],
    composition: ["16:9 with goblins in foreground, Rose anxious but unharmed, party controlling the scene."],
    timelineOverrides: ["Barry still has no crossbow."],
    pathCompatibility: ["The goblin handling can differ by route, so avoid showing coins, a completed bribe or a finished fight as the only interpretation."],
    avoid: ["No gore, no oversized ogres, no cartoon goblins, no crossbow on Barry."],
  },
  {
    id: "ch6-cave-prep",
    chapterId: "ch6",
    triggerSceneId: "Ch6-Intro",
    title: "Preparing near the cave",
    characters: ["barry", "daren", "kate", "rose"],
    settingFacts: ["Sunny cave entrance and surrounding Varathian forest at noon, clear sky, rough stone mouth and natural ground."],
    actionFacts: ["Barry, Daren, Kate and Rose finish a strategy meeting in a circle before preparing to leave."],
    materialDetails: ["Barry still has no visible crossbow at this exact early ch6 preparation moment."],
    unnamedCharacters: [],
    composition: ["16:9 group composition at the cave entrance, naturalistic and readable."],
    timelineOverrides: ["Barry has no crossbow until the later `Ch6-Packing` moment."],
    pathCompatibility: ["Elaria and Molan are not part of this trigger scene; keep the image focused on the four-person strategy pause at the cave entrance."],
    avoid: ["No dragon yet, no crossbow on Barry, no fortress, no Elaria or Molan in this moment."],
  },
  {
    id: "ch6-barry-packing-crossbow",
    chapterId: "ch6",
    triggerSceneId: "Ch6-Packing",
    title: "Barry packs the crossbow",
    characters: ["barry", "daren", "rose"],
    settingFacts: ["Travel-prep scene near the cave route or just after leaving it, practical gear on the ground, forest and stone around the group."],
    actionFacts: ["Barry takes spoils from earlier fights, straps the crossbow to the back of his backpack, and Daren enchants the backpack shortly after noticing it is ordinary."],
    materialDetails: [
      "Show the backpack clearly as practical and ordinary before Daren's enchantment, with the crossbow newly strapped to it.",
      "Daren may be shown in the act of enchanting it: yellow eyes, hands near the backpack and a contained glow on the bag during the spell.",
      "Barry's stat device stays in his pocket here; the visual focus is the first backpack-crossbow silhouette, not the handheld device.",
    ],
    unnamedCharacters: [],
    composition: ["16:9 gear-focused scene, full-body Barry kneeling or standing with backpack and crossbow clearly readable."],
    timelineOverrides: ["This is the first moment where Barry's crossbow should appear."],
    pathCompatibility: ["Elaria and Molan are present only on some routes, so do not require them. Focus on the shared facts of Barry collecting gear, Daren enchanting the backpack, Rose nearby and the first crossbow-on-backpack silhouette."],
    barryEquipment: { statDevice: "pocket", backpack: "transition" },
    avoid: ["No earlier heroic crossbow use, no modern tactical backpack, no gun-like redesign, no backpack inventory screen."],
  },
  {
    id: "ch6-tyrath-arrival",
    chapterId: "ch6",
    triggerSceneId: "Ch6-Dragon",
    title: "Tyrath arrives",
    characters: ["barry", "daren", "kate", "rose", "tyrath"],
    settingFacts: ["Open forest clearing or cave-adjacent wilderness with sky exposure, violent wind, bending trees and sudden scale shift from dragon arrival."],
    actionFacts: ["Tyrath appears high above as a massive red dragon while the party realizes the danger and braces against the wind."],
    materialDetails: ["Tyrath needs wings, armored scales, claws and internal fire glow; keep him fully dragon."],
    unnamedCharacters: [],
    composition: ["16:9 scale scene: dragon huge, party small but identifiable; Barry may now have crossbow on backpack."],
    timelineOverrides: ["Barry can now have the crossbow strapped to his backpack."],
    barryEquipment: { statDevice: "in-hand" },
    avoid: ["No humanoid dragonborn, no saddle, no city kaiju shot."],
  },
  {
    id: "ch6-time-weaver",
    chapterId: "ch6",
    triggerSceneId: "Ch6-Time-weaver",
    title: "Time Weaver pressure",
    characters: ["barry", "daren", "kate", "rose", "tyrath"],
    settingFacts: ["Dragon battlefield with distorted air, time-pressure atmosphere and torn terrain."],
    actionFacts: ["The party faces impossible pressure from Tyrath while Barry's stat-device choices and timing matter."],
    materialDetails: ["Use restrained time-distortion rings or fractured motion trails, not sci-fi holograms."],
    unnamedCharacters: [],
    composition: ["Dynamic 16:9, Tyrath as looming threat, party braced in a tight cluster."],
    timelineOverrides: ["Barry can have crossbow on backpack, but do not make him a trained archer."],
    pathCompatibility: ["The preceding answer to Eiden changes dialogue context, so depict battlefield pressure and time distortion rather than a specific spoken answer."],
    barryEquipment: { statDevice: "in-hand" },
    avoid: ["No superhero time suit, no modern clock UI, no readable text."],
  },
  {
    id: "ch7-diane-tension",
    chapterId: "ch7",
    triggerSceneId: "Ch7-Diane",
    title: "Kate accuses Barry over Diane",
    characters: ["barry", "kate"],
    settingFacts: ["Forest route before the sacred-woods encounter, quiet but emotionally charged, with ordinary trees around Barry and Kate."],
    actionFacts: ["Kate confronts Barry in anger and fear while speaking about Diane; Diane herself is not visible yet in this trigger scene."],
    materialDetails: ["Kate's dagger and tense posture may be visible; Barry remains under-equipped and defensive rather than heroic."],
    unnamedCharacters: [],
    composition: ["16:9 close character confrontation, Kate intense and wounded, Barry cautious and trying to de-escalate."],
    timelineOverrides: ["Barry can have crossbow on backpack from this point onward."],
    pathCompatibility: ["The scene differs depending on whether Barry tapped Kate earlier, so keep the visual to Kate's accusation and avoid a precise route-specific injury or dialogue beat."],
    avoid: ["No visible Diane yet, no electricity reveal yet, no fire magic, no romantic softness."],
  },
  {
    id: "ch7-hadrik-giant",
    chapterId: "ch7",
    triggerSceneId: "Ch7-Giant",
    title: "Hadrik reveals his giant truth",
    characters: ["barry", "daren", "kate", "hadrik"],
    settingFacts: ["Tournament wilderness gathering area with room for a massive scale reveal."],
    actionFacts: ["Hadrik's giant nature should be implied through scale, shadow or transformation while preserving his dwarf-form identity."],
    materialDetails: ["Leather armor, black beard, big grin and heavy dwarf body should remain consistent."],
    unnamedCharacters: ["Optional shocked mage silhouettes for scale."],
    composition: ["16:9, Hadrik as massive personality and scale focal point, party reacting."],
    timelineOverrides: ["Barry can have crossbow on backpack."],
    avoid: ["No elegant noble dwarf, no clean ceremonial armor, no making Hadrik harmless."],
  },
  {
    id: "ch7-azarius-duel",
    chapterId: "ch7",
    triggerSceneId: "Ch7-Wait",
    title: "Azarius presides over the chaos",
    characters: ["barry", "hadrik", "azarius"],
    settingFacts: ["Crowded tournament clearing with mages at a careful distance, dust, trampled grass and public tension."],
    actionFacts: ["Azarius, the elderly Sage of the West, imposes authority while Hadrik prepares for conflict."],
    materialDetails: ["Azarius must have white beard, wooden staff, traditional robes and pointed hat; do not confuse him with Felran."],
    unnamedCharacters: ["Background tournament mages, restrained and wary, no unique named designs."],
    composition: ["16:9 crowd-control scene, Azarius authoritative, Hadrik broad and impatient."],
    timelineOverrides: ["Barry can have crossbow on backpack if visible."],
    avoid: ["No red fire robes on Azarius, no young wizard styling."],
  },
  {
    id: "ch7-hadrik-vs-felran",
    chapterId: "ch7",
    triggerSceneId: "Ch7-Dwarf-vs-fire",
    title: "Hadrik against Felran's fire",
    characters: ["barry", "hadrik", "azarius"],
    settingFacts: ["Tournament clearing transformed into a fire-lit duel zone, scorched dirt and crowd pulled back."],
    actionFacts: ["Hadrik charges or endures a fire mage's attack while Azarius and others watch the situation."],
    materialDetails: ["Felran is an anonymous red/fire mage here unless no portrait exists: red-toned robes, fire magic, aggressive stance."],
    unnamedCharacters: ["Felran as unnamed fire mage opponent, plus distant mages as witnesses."],
    composition: ["16:9 action duel, Hadrik grounded and physical, fire mage opposite, watchers behind."],
    timelineOverrides: ["Barry can have crossbow on backpack if present but should not dominate."],
    avoid: ["Do not style Azarius as Felran; no gore, no modern arena."],
  },
  {
    id: "ch8-prison-collars",
    chapterId: "ch8",
    triggerSceneId: "Ch8-Intro2",
    title: "Captured by the animal kingdom",
    characters: ["barry", "daren", "kate", "rose", "hadrik"],
    settingFacts: ["Ancient ruin prison or holding area, old stone, a cell-like space, green collars with strange markings and restrained movement."],
    actionFacts: ["The party wakes or stands captured with magical collars, confused and unable to act freely."],
    materialDetails: ["Collars should look magical but ancient, not modern shock collars; ruins should feel old and functional."],
    unnamedCharacters: ["A tiger and a bear guard may be hinted only if useful, as natural animals rather than humanoids."],
    composition: ["16:9 restrained group scene, collars readable, ruins architecture important."],
    timelineOverrides: ["Barry can have crossbow on backpack but the collar and captivity are the main visual facts."],
    avoid: ["No dungeon torture imagery, no humanoid animal guards, no modern prison bars."],
  },
  {
    id: "ch8-eleya-judgment",
    chapterId: "ch8",
    triggerSceneId: "Ch8-Talk2",
    title: "Eleya judges the intruders",
    characters: ["barry", "daren", "kate", "rose", "hadrik", "eleya", "leo", "taurus"],
    settingFacts: ["Ancient ruin prison corridor in front of the party's cell, old stone floor and golden magical pressure from Eleya's aura."],
    actionFacts: ["Eleya the golden fox judges the party with Leo the leopard and Taurus the bull at her side."],
    materialDetails: ["Eleya is a natural golden fox with brilliant aura; Leo and Taurus are natural animals, disciplined lieutenants."],
    unnamedCharacters: [],
    composition: ["16:9 formal judgment scene, Eleya small but visually dominant through golden aura, party lower or restrained."],
    timelineOverrides: ["Barry can have crossbow on backpack, but collars and Eleya's authority dominate."],
    avoid: ["No humanoid fox woman, no minotaur Taurus, no anthropomorphic Leo, no cute pet staging."],
  },
  {
    id: "ch8-flower-training",
    chapterId: "ch8",
    triggerSceneId: "Ch8-Training",
    title: "Flower drops into the ruined room",
    characters: ["barry", "daren", "kate", "rose", "hadrik", "flower"],
    settingFacts: ["Ancient ruin corridor or training room with traps, walls, tunnels and enough vertical space for Flower's acrobatic movement."],
    actionFacts: ["Flower appears agile and energetic, dropping or flipping through the space while the party notices her amulet."],
    materialDetails: ["Flower's golden amulet must be visible because Arraka is represented through it."],
    unnamedCharacters: [],
    composition: ["16:9 vertical-energy scene, Flower full-body acrobatic pose, party watching from below or side."],
    timelineOverrides: ["Only Flower's body is visible here, not a separate Illuna body."],
    avoid: ["No adult Flower, no shoes, no separate Arraka body, no sexualized framing."],
  },
  {
    id: "ch8-hydra-room",
    chapterId: "ch8",
    triggerSceneId: "Ch8-Hydra",
    title: "The hydra trap",
    characters: ["barry", "daren", "kate", "rose", "hadrik"],
    settingFacts: ["Ancient trap room with stone floor, ruin mechanisms, a hole in the roof or upper opening, and enough scale for the hydra threat."],
    actionFacts: ["A hydra blocks or attacks the party in the ruins while Daren calls for Flower through the roof opening, but she is not visible in the room."],
    materialDetails: ["Hydra should be multi-headed, reptilian and dangerous, with no humanoid traits."],
    unnamedCharacters: ["Hydra as unnamed monster, ancient trap mechanisms."],
    composition: ["16:9 action scene with hydra heads framing the party, readable scale and architecture."],
    timelineOverrides: ["Barry can have crossbow on backpack, but not a superhero archer stance."],
    pathCompatibility: ["The hearing stat changes the available response, so show the hydra threat and room layout without implying whether Barry heard the key detail."],
    avoid: ["No visible Flower in the room, no dragon confusion with Tyrath, no gore, no cartoon hydra."],
  },
  {
    id: "ch8-control-room",
    chapterId: "ch8",
    triggerSceneId: "Ch8-Control-room",
    title: "The ancient control room",
    characters: ["barry", "daren", "kate", "rose", "hadrik", "flower", "eleya", "leo"],
    settingFacts: ["Large ancient control room, stone and strange machinery, levers, buttons, inscriptions and bright golden magical effects."],
    actionFacts: ["Flower stops at the corridor exit as the party enters the bright control room where Eleya the golden fox and Leo the leopard are waiting."],
    materialDetails: [
      "Show only Flower's little-girl body here; do not switch her to Illuna's blue-eyed state unless the scene specifically asks for Illuna.",
      "Arraka remains represented through the golden amulet, not a separate person.",
    ],
    unnamedCharacters: ["Ancient mechanisms, levers and control surfaces with no readable text."],
    composition: ["16:9 architectural scene, control room depth, Eleya's overwhelming golden aura and the later golden cage/control magic as focal environment."],
    timelineOverrides: ["Flower is the visible state of the shared body here; never show Flower and Illuna as two visible girls."],
    pathCompatibility: ["Earlier talk choices change context, so focus on the shared control room, Eleya, Leo, single shared body, amulet and golden control magic rather than a specific line of dialogue."],
    avoid: ["No sci-fi spaceship bridge, no readable inscriptions, no duplicate Flower/Illuna bodies."],
  },
  {
    id: "ch9-stronghold-road",
    chapterId: "ch9",
    triggerSceneId: "Ch9-Intro",
    title: "Road toward the ogre stronghold",
    characters: ["barry", "daren", "kate", "rose", "hadrik", "flower"],
    settingFacts: ["Wild terrain route away from the ruins toward ogre lands, first following a path and later moving through less marked terrain."],
    actionFacts: ["The group travels together, tired but moving with purpose toward the stronghold."],
    materialDetails: ["Travel packs, worn boots and practical marching spacing should be visible."],
    unnamedCharacters: [],
    composition: ["Wide 16:9 journey shot with the party in a staggered line, landscape leading forward."],
    timelineOverrides: ["Barry can have crossbow on backpack."],
    avoid: ["No fortress interior yet, no city, no cheerful picnic energy."],
  },
  {
    id: "ch9-flower-illuna-origin",
    chapterId: "ch9",
    triggerSceneId: "Ch9-Awakening",
    title: "Flower and Illuna's shared origin",
    characters: ["barry", "flower"],
    settingFacts: ["Quiet forest-path conversation during the journey toward the ogre stronghold, intimate rather than action-heavy."],
    actionFacts: ["Flower discusses sharing one body with Illuna/Petal; keep the image as present-time conversation rather than a memory scene."],
    materialDetails: ["Use one body, long red hair, gray tank top, clown-like pants, bare feet and golden amulet."],
    unnamedCharacters: [],
    composition: ["16:9 reflective character scene, one body with a thoughtful or dual-mood expression, not two separate bodies."],
    timelineOverrides: ["Flower is the only visible state here; Illuna/Petal is discussed, not physically shown or attached as a separate reference."],
    pathCompatibility: ["The exact backstory wording changes with previous knowledge, so keep the image focused on the present conversation, Flower's single body and the amulet."],
    avoid: ["No Illuna reference image attached, no duplicate girls, no adult body, no horror possession cliché, no separate Arraka body."],
  },
  {
    id: "ch9-enchanted-backpack",
    chapterId: "ch9",
    triggerSceneId: "Ch9-Backpack",
    title: "Barry discovers the enchanted backpack",
    characters: ["barry", "kate", "hadrik"],
    settingFacts: ["Morning camp as tents are being dismantled, sunrise light, backpacks and travel gear being packed before departure."],
    actionFacts: ["Barry tries to inventory his enchanted backpack and Kate shows him how to make the item-list screen appear."],
    materialDetails: [
      "Backpack should look ordinary outside but subtly enchanted, with a magical inventory screen or glow.",
      "Crossbow is strapped to the backpack now; Barry's stat device stays in his pocket because the magical inventory belongs to the backpack, not the handheld device.",
    ],
    unnamedCharacters: [],
    composition: ["16:9 gear close-scene, backpack and Barry full-body visible, Kate close enough to demonstrate the tap, Hadrik secondary if present."],
    timelineOverrides: ["Barry has crossbow on backpack; backpack enchantment is now visible."],
    pathCompatibility: ["The inventory explanation can differ by route, so show the backpack screen appearing without readable item names or a route-specific item list."],
    barryEquipment: { statDevice: "pocket", backpack: "enchanted-visible" },
    avoid: ["No modern laptop/tablet UI, no readable item text, no sci-fi inventory grid."],
  },
  {
    id: "ch9-ogre-ambush",
    chapterId: "ch9",
    triggerSceneId: "Ch9-Muffled",
    title: "The deserted ogre stronghold trap",
    characters: ["barry", "daren", "kate", "rose", "hadrik", "flower"],
    settingFacts: ["Ogre stronghold on a hill, cleared of trees and vegetation around it, thirty-foot stone walls, wide open wooden gate and deserted inner yard."],
    actionFacts: ["The party enters cautiously through the open gate while Arraka's amulet makes muffled warning noises and Flower refuses to open it."],
    materialDetails: ["Show the square fortress layout, rough stone walls, central building connected to the walls and empty yard; keep the trap implied by absence."],
    unnamedCharacters: ["No visible ogres yet; the threat is the suspicious emptiness and the muffled amulet warning."],
    composition: ["16:9 wide fort approach/interior-yard scene, open gate and empty yard dominant, party small and wary."],
    timelineOverrides: ["Barry has crossbow on backpack but should not solve the scene visually."],
    pathCompatibility: ["The ogre reveal happens after this trigger, so keep this moment to the deserted stronghold and Arraka's warning rather than the later visible encirclement."],
    avoid: ["No visible ogres yet, no comic ogres, no gore, no forest ambush, no closed castle gate."],
  },
  {
    id: "ch9-illuna-golden-cage",
    chapterId: "ch9",
    triggerSceneId: "Ch9-Submission",
    title: "Illuna's golden cage",
    characters: ["barry", "daren", "kate", "rose", "hadrik", "illuna"],
    settingFacts: ["Inside the ogre fort yard after the ogres reveal themselves, with the group surrounded and the shaman pressuring them."],
    actionFacts: ["Illuna takes over the shared body with bright blue eyes and creates a golden cage around the party, leaving herself outside with the ogres."],
    materialDetails: ["Only one little girl's body is visible; the golden amulet holding Arraka and Illuna's bright blue eyes are the identity switch."],
    unnamedCharacters: ["Ogre shaman, armored captain and surrounding ogres may be present as background threats outside the cage."],
    composition: ["16:9 magical containment scene, one small body visually powerful without adult proportions."],
    timelineOverrides: ["Use Illuna state, not Flower's warm expression; no separate Petal."],
    avoid: ["No duplicate body, no adult Illuna, no sexualized child framing, no dark villain robe."],
  },
  {
    id: "ch10-ogre-plan",
    chapterId: "ch10",
    triggerSceneId: "Ch10-Treasury",
    title: "Planning inside the ogre fortress",
    characters: ["barry", "daren", "kate", "rose", "hadrik", "illuna"],
    settingFacts: ["Ogre fortress treasure room at the lowest level of the main building, rough stone interior, mountains of gold and coffers of jewels."],
    actionFacts: ["The group pauses around a treasury or plan point while Arraka/Illuna's guidance complicates the mood."],
    materialDetails: ["Treasure can be abundant gold, gems and fineries inside a rough ogre-held fortress; Arraka remains the amulet."],
    unnamedCharacters: ["Ogre-made architecture and rough storage objects, no active ogres needed."],
    composition: ["16:9 tactical group scene, low fortress lighting, treasure and rough stone readable."],
    timelineOverrides: ["Barry has crossbow on backpack; Flower/Illuna body is in Illuna state if she is active."],
    avoid: ["No polished castle treasury, no duplicate Flower and Illuna, no readable map text."],
  },
  {
    id: "ch10-pit-rescue",
    chapterId: "ch10",
    triggerSceneId: "Ch10-Teleport",
    title: "The lower chamber regrouping",
    characters: ["daren", "illuna", "barry", "kate", "rose", "hadrik"],
    settingFacts: ["Rough fortress service chamber with stone walls, heavy wooden supports, dusty floorboards and dim torchlight."],
    actionFacts: ["Daren and Illuna stand safely with the party after a sudden repositioning; everyone is upright, alert and recovering their focus."],
    materialDetails: ["Illuna's shared body has bright blue eyes and bare feet; Daren's heavy armor is dusty, with his sword and shield held low in a calm stance."],
    unnamedCharacters: ["Crude fortress construction materials, old planks, rope bundles and rough beam supports in the background."],
    composition: ["16:9 quiet aftermath group scene, all characters on one stable floor level, Daren and Illuna near center, party gathered around them."],
    timelineOverrides: ["Only one Flower/Illuna body; use Illuna state with controlled, serious focus."],
    avoid: ["Calm non-graphic regrouping composition, one shared Flower/Illuna body only, stable floor, restrained magical atmosphere."],
  },
  {
    id: "ch10-ritual-wolves",
    chapterId: "ch10",
    triggerSceneId: "Ch10-Wolves",
    title: "Red eyes in the ritual fog",
    characters: ["barry", "daren", "kate", "rose", "hadrik", "illuna"],
    settingFacts: ["Forest edge after the ritual fog has mostly disappeared, with tree depth and red eyes visible beyond the group."],
    actionFacts: ["Oversized black wolf silhouettes reveal themselves at the edge of the woods while the party notices them and forms a cautious line; show suspense before any attack."],
    materialDetails: ["Wolves are at least three times the size of normal wolves, with fur as black as coal and red eyes; they are not werewolves."],
    unnamedCharacters: ["Several oversized black wolves in the forest depth, kept as looming silhouettes with readable red eyes; no detailed shaman portrait unless needed."],
    composition: ["16:9 suspense scene, red eyes in background, party in cautious line foreground, weapons held without contact."],
    timelineOverrides: ["Barry has crossbow on backpack but should look cautious and outmatched."],
    avoid: ["No werewolves, no cartoon red eyes; keep all figures separated and keep the wolves at a distance."],
  },
  {
    id: "ch10-after-ogres",
    chapterId: "ch10",
    triggerSceneId: "Ch10-Toast",
    title: "The tired camp after the ogres",
    characters: ["barry", "daren", "kate", "rose", "hadrik", "illuna"],
    settingFacts: ["Travel camp after leaving the ogre fort and marching back toward the sacred woods, with tents set near a good camping spot and no active battle."],
    actionFacts: ["The tired group sets up tents after Illuna helps Kate practice suppressing her aura, while Hadrik suggests a toast to celebrate their victory; most are too exhausted to drink."],
    materialDetails: ["Tents, travel gear, tired faces, restrained celebratory mood; do not invent moon, stars or dramatic night sky details."],
    unnamedCharacters: [],
    composition: ["16:9 quiet camp scene, Hadrik holding or suggesting ale, party exhausted and seated or finishing the tents."],
    timelineOverrides: ["Use Illuna as the visible state of the shared body here because the scene focuses on Illuna helping Kate practice aura suppression; do not show Flower separately."],
    avoid: ["No spoiler of Eiden yet in this image, no duplicate shared body, no bright tavern mood."],
  },
  {
    id: "ch10-eiden-confrontation",
    chapterId: "ch10",
    triggerSceneId: "Ch10-Ending",
    title: "Eiden confronts Barry",
    characters: ["barry", "eiden", "rose", "daren", "kate", "hadrik", "flower"],
    settingFacts: ["Camp-edge confrontation after breakfast and packing, with tents or camp gear nearby and ordinary wilderness around the group."],
    actionFacts: ["Eiden calmly threatens Barry's friends; Rose struggles for breath, others are immobilized, and Flower stands shocked near shattered plates before her rage erupts."],
    materialDetails: ["Eiden has eyes closed, hands in pockets and loose clothes; Barry is panicked, while Flower's shared body and golden amulet remain one visual figure."],
    unnamedCharacters: [],
    composition: ["16:9 psychological standoff, Eiden relaxed and terrifying, Barry vulnerable, Rose and immobilized companions readable but non-graphic, shattered plates near Flower."],
    timelineOverrides: ["Show Flower as the visible state before her rage erupts; do not show Illuna as a second figure. Barry may have crossbow on backpack but should not look capable of winning by force."],
    avoid: ["No open-eyed Eiden, no lightning battle pose, no duplicate girl, no readable text."],
  },
  {
    id: "ch11a-thilias-gates",
    chapterId: "ch11a",
    triggerSceneId: "Ch11a-Luxurious",
    title: "The real Thilias",
    characters: ["barry", "daren", "kate", "rose", "hadrik", "flower"],
    settingFacts: ["Entrance into Thilias with contrast between expected luxury and rough poor wooden houses, cramped streets and tired civilians."],
    actionFacts: ["The party enters the city and sees the poorer reality behind Thilias' reputation."],
    materialDetails: ["Buildings should use worn wood, patched structures, narrow street surfaces and modest town clutter."],
    unnamedCharacters: ["Civilian townspeople in simple clothes, no named focus."],
    composition: ["16:9 establishing city moment, party foreground, city texture and poverty visible."],
    timelineOverrides: ["Barry has crossbow on backpack; Flower/Illuna still one body."],
    avoid: ["No shining capital city, no palace street, no modern storefronts."],
  },
  {
    id: "ch11a-eiden-slavery-intervention",
    chapterId: "ch11a",
    triggerSceneId: "Ch11a-Power",
    title: "Eiden intervenes in Thilias",
    characters: ["barry", "daren", "kate", "rose", "hadrik", "flower", "eiden"],
    settingFacts: ["Thilias street with civilian poverty, oppressive social order and a tense public scene."],
    actionFacts: ["Eiden's calm intervention changes the power balance while the party witnesses the city's cruelty."],
    materialDetails: ["Depict oppression through posture, distance and street staging, not exploitative imagery."],
    unnamedCharacters: ["Nobles or guards in better clothes, poor civilians in worn clothing; keep them background."],
    composition: ["16:9 street scene, Eiden calm in loose clothes, party uneasy, social contrast visible."],
    timelineOverrides: ["Barry has crossbow on backpack."],
    pathCompatibility: ["The player may intervene in different ways before Eiden changes the situation, so show Eiden's calm disruption and the street power imbalance without a single route-specific action."],
    avoid: ["No graphic abuse, no fetishized slavery imagery, no heroic glowing Eiden."],
  },
  {
    id: "ch11a-rose-home",
    chapterId: "ch11a",
    triggerSceneId: "Ch11a-Toy",
    title: "Rose's home and Suzie's toy",
    characters: ["barry", "rose", "suzie", "daren", "hadrik"],
    settingFacts: ["Rose's Thilias mansion or large home, with a main hall, yard or picnic tables nearby, comfortable domestic details and no palace luxury."],
    actionFacts: ["Suzie guards or trades her small virtual-pet-like toy while Barry compares it to his stat device and the group settles into Rose's home."],
    materialDetails: ["The toy should resemble a small virtual-pet device, not a modern smartphone; muffins and home clutter matter."],
    unnamedCharacters: [],
    composition: ["16:9 domestic scene near the main hall, yard or picnic tables, Rose and Suzie central, Barry with the device trade if that route is represented."],
    timelineOverrides: ["Barry still has his backpack at Rose's home, but the toy/stat-device comparison is the main prop."],
    pathCompatibility: ["Suzie's toy interaction can vary depending on earlier city choices, so keep the image to the warm home setting, muffins and the small virtual-pet toy without fixing a specific exchange."],
    avoid: ["No poor shack, no royal palace, no modern phone, no combat pose."],
  },
  {
    id: "ch11a-beggars-district-trap",
    chapterId: "ch11a",
    triggerSceneId: "Ch11a-Incriminated",
    title: "Returning through the Beggar's district",
    characters: ["barry", "daren", "kate", "rose", "hadrik", "flower"],
    settingFacts: ["Beggar's district street in Thilias, foul-smelling poor area with worn wooden houses and people in rags or worn clothing."],
    actionFacts: ["The party walks with Rose while Kate questions whether Rose should be seen with wanted outsiders."],
    materialDetails: ["Show social unease and poverty through posture, distance, worn clothing and streetscape; Zack is not visible in this trigger scene."],
    unnamedCharacters: ["Poor civilians may watch uneasily from the street or doorways, but no attacking crowd yet."],
    composition: ["16:9 tense walking scene through the district, Rose leading or explaining, party alert but not yet ambushed."],
    timelineOverrides: ["Barry left his backpack behind before going downtown; Flower/Illuna body is one person."],
    barryEquipment: { statDevice: "pocket", backpack: "not-carried" },
    pathCompatibility: ["This trigger is before the clone ambush; keep it to the shared return through the district and the discussion about legal incrimination."],
    avoid: ["No Zack yet, no clone ambush yet, no modern city alley, no excessive gore, no unreadable crowd clutter, no backpack or crossbow on Barry."],
  },
  {
    id: "ch11b-clone-ambush",
    chapterId: "ch11b",
    triggerSceneId: "Ch11b-Clones",
    title: "Magical duplicates confuse the Thilias street",
    characters: ["barry", "daren", "kate", "rose", "hadrik", "flower"],
    settingFacts: ["Thilias market or poor district transition, public space disrupted by magical duplicates and confusion."],
    actionFacts: ["Repeated magical silhouettes appear at different distances around Rose and the party, creating uncertainty and separation while everyone remains apart."],
    materialDetails: ["Illusion figures should look uncanny through repeated silhouettes and subtle magical distortion, not sci-fi holograms."],
    unnamedCharacters: ["Duplicate illusion figures and background civilians keeping distance from the confusing scene."],
    composition: ["16:9 magical confusion scene, repeated forms and party reactions readable, with clear spacing between figures."],
    timelineOverrides: ["Barry left his backpack behind before this city sequence; no backpack or crossbow on him."],
    barryEquipment: { statDevice: "pocket", backpack: "not-carried" },
    avoid: ["No neon sci-fi clones, no crowded pileup, keep figures separated, no unreadable crowd, no backpack or crossbow on Barry."],
  },
  {
    id: "ch11b-skeletal-dragon",
    chapterId: "ch11b",
    triggerSceneId: "Ch11b-Monster",
    title: "The skeletal dragon threat",
    characters: ["barry", "daren", "kate", "hadrik", "zack"],
    settingFacts: ["Thilias battle space with cracked pavement, market debris and dark necromantic pressure."],
    actionFacts: ["A skeletal dragon or death-magic monster becomes the central threat while the party braces."],
    materialDetails: ["Monster should be skeletal and necromantic, distinct from living Tyrath; do not add a separate Arraka body."],
    unnamedCharacters: ["Skeletal dragon/death monster and fleeing civilians in distance."],
    composition: ["16:9 large-monster battle scene, skeletal form towering over grounded party."],
    timelineOverrides: ["Barry left his backpack behind before this city ambush; he remains vulnerable without backpack or crossbow."],
    barryEquipment: { statDevice: "pocket", backpack: "not-carried" },
    avoid: ["Do not reuse Tyrath as a living dragon, no excessive gore, no cartoon skeleton, no backpack or crossbow on Barry."],
  },
  {
    id: "ch11b-zack-sacrifice",
    chapterId: "ch11b",
    triggerSceneId: "Ch11b-Sacrificial",
    title: "Zack's sacrificial ritual",
    characters: ["barry", "daren", "kate", "hadrik", "zack"],
    settingFacts: ["Battle-damaged Thilias square or street, dark ritual atmosphere, debris and frightened distance."],
    actionFacts: ["Zack performs a sacrificial death-magic act; show ritual red/dark light and posture without graphic injury."],
    materialDetails: ["Black robes and snake tattoo must be visible; ritual energy should feel death-cult, not generic fire."],
    unnamedCharacters: ["Civilians or enemies distant, obscured by ritual light."],
    composition: ["16:9 ritual climax, Zack focal but non-graphic, party reacting from safe distance."],
    timelineOverrides: ["Barry left his backpack behind before this city ambush; no backpack or crossbow on him."],
    pathCompatibility: ["The party's strategy can change who is positioned where, so show Zack's non-graphic ritual energy and broad party reaction without locking exact tactical placement."],
    barryEquipment: { statDevice: "pocket", backpack: "not-carried" },
    avoid: ["No explicit stabbing wound, no gore, no satanic modern symbols, no readable text, no backpack or crossbow on Barry."],
  },
  {
    id: "ch11b-golmyck-announcement",
    chapterId: "ch11b",
    triggerSceneId: "Ch11b-Ending",
    title: "Golmyck appears on giant screens",
    characters: ["barry", "daren", "kate", "rose", "hadrik", "flower", "golmyck"],
    settingFacts: ["Thilias public square after the battle, damaged market elements, civilians and giant magical/mechanical display screens."],
    actionFacts: ["Golmyck appears on large screens to announce the first tournament objectives while the party looks up."],
    materialDetails: ["Screens should be fantasy-mechanical or magical projection devices, with no readable text."],
    unnamedCharacters: ["Civilians and tournament participants watching the announcement."],
    composition: ["16:9 aftermath announcement, party foreground looking up, Golmyck's projected face or figure on screens."],
    timelineOverrides: ["Barry left his backpack behind before this city ambush; Flower/Illuna body should use the currently relevant expression only."],
    barryEquipment: { statDevice: "pocket", backpack: "not-carried" },
    avoid: ["No modern LED billboard, no readable subtitles, no clean futuristic city, no backpack or crossbow on Barry."],
  },
];
